name: Android CI

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JAVA_HOME: /usr/lib/jvm/temurin-17-jdk-amd64

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Оптимизация: кеширование Gradle (~30% ускорение сборки)
    - name: Cache Gradle
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle-wrapper.properties') }}

    # Используем существующий gradlew (если он есть) или генерируем новый
    - name: Set up Gradle Wrapper
      run: |
        if [ -f "gradlew" ]; then
          echo "✅ gradlew уже существует в проекте"
        else
          echo "⚙️ Генерация Gradle Wrapper..."
          gradle wrapper --gradle-version 8.2 --distribution-type bin
        fi
        chmod +x gradlew

    - name: Clean project
      run: ./gradlew clean

    # Фикс для AndroidManifest.xml (если требуется)
    - name: Fix AndroidManifest.xml
      run: |
        if [ -f "app/src/main/AndroidManifest.xml" ]; then
          if ! grep -q 'android:exported=' app/src/main/AndroidManifest.xml; then
            sed -i '/<activity.*android:name=".MainActivity"/a \        android:exported="true"' app/src/main/AndroidManifest.xml
            echo "🛠 Добавлен android:exported в MainActivity"
          fi
        else
          echo "⚠️ Файл AndroidManifest.xml не найден!"
        fi

    - name: Build APK
      run: |
        ./gradlew assembleDebug --stacktrace --info

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 3
