name: Android CI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JAVA_HOME: /usr/lib/jvm/temurin-17-jdk-amd64

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle Wrapper
      run: |
        # Создаем минимальную структуру Gradle
        if [ ! -f settings.gradle ]; then
          echo "rootProject.name = 'IntegerSynth'" > settings.gradle
          echo "include ':app'" >> settings.gradle
        fi

        # Скачиваем официальный Gradle Wrapper
        mkdir -p gradle/wrapper
        curl -fsSL https://raw.githubusercontent.com/gradle/gradle/v8.2/gradlew -o gradlew
        curl -fsSL https://raw.githubusercontent.com/gradle/gradle/v8.2/gradlew.bat -o gradlew.bat
        curl -fsSL https://github.com/gradle/gradle/raw/v8.2/gradle/wrapper/gradle-wrapper.jar -o gradle/wrapper/gradle-wrapper.jar
        
        # Конфигурация wrapper
        cat > gradle/wrapper/gradle-wrapper.properties <<EOL
        distributionBase=GRADLE_USER_HOME
        distributionPath=wrapper/dists
        distributionUrl=https\://services.gradle.org/distributions/gradle-8.2-bin.zip
        zipStoreBase=GRADLE_USER_HOME
        zipStorePath=wrapper/dists
        EOL

        # Права и проверка
        chmod +x gradlew
        ./gradlew --version || echo "Gradle check failed but continuing"

    - name: Fix Android Manifest
      run: |
        # Создаем манифест если его нет
        if [ ! -f app/src/main/AndroidManifest.xml ]; then
          mkdir -p app/src/main
          cat > app/src/main/AndroidManifest.xml <<EOL
        <?xml version="1.0" encoding="utf-8"?>
        <manifest xmlns:android="http://schemas.android.com/apk/res/android"
            package="com.example.integerprogressionsynth">
            <application>
                <activity android:name=".MainActivity" android:exported="true">
                    <intent-filter>
                        <action android:name="android.intent.action.MAIN" />
                        <category android:name="android.intent.category.LAUNCHER" />
                    </intent-filter>
                </activity>
            </application>
        </manifest>
        EOL
        fi

        # Добавляем exported если отсутствует
        sed -i '/<activity.*MainActivity/ { /android:exported/! s/$/ android:exported="true"/ }' app/src/main/AndroidManifest.xml
        cat app/src/main/AndroidManifest.xml

    - name: Build APK
      run: |
        # Чистка и сборка
        ./gradlew clean
        ./gradlew assembleDebug --stacktrace --no-daemon

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 3
